### ISSUE TITLE
When will the paper code be open sourced?

### ISSUE THREAD

**Issue by Pddp-edg** [JinglinZhan/Real-Aug#1]
Hello, 
&emsp; I am very interested in the method proposed in the paper Real-aug. I wonder when the relevant code of the paper will be uploaded?

**Comment by JinglinZhan** [comment]
Thanks for your interest. We will release the code after the corresponding paper is accepted.

**Comment by JinglinZhan** [comment]
> Hello,   I am very interested in the method proposed in the paper Real-aug. I wonder when the relevant code of the paper will be uploaded?

Thanks for your interest. We will release the code after the corresponding paper is accepted.
